apiVersion: v1
kind: Pod
metadata:
  name: test-sample-pod
spec:
  containers:
    - image: busybox
      name: test-sample-ctr
      resources:
        limits:
          aios/sample: 1
        requests:
          aios/sample: 1
      command:
        - sleep
        - "10000000"
